### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by LeviAckerman1234** [lkaesberg/EmailVerify#13]
I get saying messageactionrow does not work when i try to use buttons command so when i updated it to discord.js 14.5.0 it keeps saying i dont have permission to write in that channel please help me when you can

**Comment by LeviAckerman1234** [comment]
also how do i setup the smtp stuff?

**Comment by LeviAckerman1234** [comment]
Why did you close the issue when you haven’t even helped me or done anything about the issue?

**Comment by lkaesberg** [comment]
> Why did you close the issue when you haven’t even helped me or done anything about the issue?

Then take a look at the following issue and provide usable information of what you want to do and why it isn't working.

https://github.com/mootools/mootools-core/issues/2833#issuecomment-1274370181

**Comment by lkaesberg** [comment]
And on top of that it seems like you have a problem that is not directly related to the EmailVerify bot but rather to some error in another library or an error in your code.
